apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask-k8s
spec:
  selector:
    matchLabels:
      app: flask-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-deployment
    spec:
      containers:
      - name: flask-deployment
        image:  002784619873.dkr.ecr.us-east-2.amazonaws.com/flask-k8s:latest
        ports:
        - containerPort: 5000
