apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-k8s
spec:
  selector:
    app: flask-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
